### ISSUE TITLE
UnitTest fails

### ISSUE THREAD

**Issue by leledumbo** [mdbs99/Greyhound#33]
Hi, I just returned to Greyhound since no other OPF currently supports M-N relationships easily.

Running the unit test, all but the first test case fails. The exception is all the same: EDatabaseError: no such table: user.
I then [combine the M-N post test and M-N test into a single project](https://dl.dropboxusercontent.com/u/22124591/Programs/t1.zip), using the links example as a base. I can reproduce the exception there. When I check the generated DB.sqlite, only the first create statement and insert statement is executed. Something seems wrong with the batch operation...

**Comment by mdbs99** [comment]
I could not reproduce this error. The test app has no errors (branch master)
What version do you use?

**Comment by leledumbo** [comment]
master branch, using FPC 3.1.1 & Lazarus 1.5 about 2 weeks old.

does the project in the link above product any exception when run?

another experiment: I run the script.sql through sqlite3 binary, and it creates the whole schema correctly. running above program then generates no exception.

**Comment by mdbs99** [comment]
When I said "no errors" I mean no errors in Greyhound branch master, not about your own sources -- I've not tested, sorry. But now I will follow your instructions written on Facebook and try to solve the problem on your source. 

I closed this issue because there is no errors here, ok?

**Comment by leledumbo** [comment]
The one in fb is different problem. The one here is still relevant to solve. I'll try to make a screencast to demonstrate the problem

**Comment by mdbs99** [comment]
Do it. But create it in a new issue, please.

**Comment by leledumbo** [comment]
Why? The problem is still the same as the title: unit test fails (on freshly checked out master branch).
Here's the screencast: https://dl.dropboxusercontent.com/u/22124591/Videos/ghtest.mp4

**Comment by mdbs99** [comment]
I didn't see what errors... could be anything, eg., if you do not have the sqlite lib in your PATH, error... so on.

I've tested here, branch master, and I have no errors. I've tested ghORM project too and no error found too.

You told me, on Facebook, about ANOTHER "problem" that I will investigate as soon as possible -- but I already told you this is not a bug, but a feature not implemented yet.

**Comment by leledumbo** [comment]
> I didn't see what errors... could be anything, eg., if you do not have the sqlite lib in your PATH, error... so on.

Won't be, this is a linux system. ghORM can access it, so does Greyhound. Because the library is in a global path. The problem is only with the setup method. SQL script fails to run correctly.

In fact, I have another interesting screencast. This is an extract from Greyhound unit test. In the screencast, I prove that script execution doesn't work right:
https://dl.dropboxusercontent.com/u/22124591/Videos/ghtest2.mp4

> You told me, on Facebook, about ANOTHER "problem" that I will investigate as soon as possible -- but I already told you this is not a bug, but a feature not implemented yet.

That one has nothing to do with this issue, they're different.

**Comment by mdbs99** [comment]
> In fact, I have another interesting screencast. This is an extract from Greyhound unit test. In the screencast, I prove that script execution doesn't work right: ...
This isn't a Greyhound's test.
1- The Greyhound's scripts are in /script directory.
2- Here is the path: https://github.com/mdbs99/Greyhound/blob/master/test/ghsqltest.pas#L72
3- There are two scripts. You copy part of code, pay attention wich script you're running.
4- Did you change the script? If yes, make sure don't forget all ";"..
5- Finally: you can run the original TestCase -- no changes -- without errors?

**Comment by leledumbo** [comment]
> This isn't the original Greyhound's test.

The original one stucks as the first screencast shows. I extracted only the MtoN_post along with setup, the code is in a link in OP. You can check yourself whether it's the same or not as the one in ghSQLtest.

>  There are two scripts. You copy part of code, make your own... that's ok, but pay attention wich script you're running.

From the output when I use sqlite3 on the console, it's very clear which script I use: only script-2 has role_user table. I do this to localize and simplify the problem.

> Did you change the script?

No. Again, see it yourself in the link in OP.

>  you can run the original TestCase -- no changes -- and tell me if you have errors?
> 
> but you couldn't change the original sources expecting that everything run smoothly but if not, say this is a bug

First video, buddy... how do you explain that? I can do the screencast again, from first `git clone`, run the test that will fail mostly and stuck and test 13, **creating DB.sqlite manually from terminal via sqlite3** and re-run the test to see that no failure/stuck occurs.

The main problem is in the **bold** part that I have to do above to make the test succeeds, ok? Stick to that point for this issue. Ignore the others. If you have teamviewer installed, you can do it yourself in realtime on my system.

**Comment by mdbs99** [comment]
Ok.
Well, as I said before, we can't see what the problem in the first screencast... but I imagine only one last thing: the FPC version.

Could you test using 2.6.5 to compare?

**Comment by mdbs99** [comment]
I'm reading this http://wiki.freepascal.org/User_Changes_Trunk#TSQLScript_supports_:.2C_backtick_quotes_and_explicit_COMMIT.2FCOMMIT_RETAIN
Maybe something was changed anyway.

**Comment by leledumbo** [comment]
I'll try upgrading first, two weeks old is enough to have bugs probably fixed. if this doesn't work, I'll downgrade then.

**Comment by mdbs99** [comment]
Now they implemented a parser for ":" -- I use my own -- and work with COMMIT... maybe using commit in script will work...

I can't use trunk version. Many times they broken the compilation or something else. I gave up. Now I use only the stable version.

**Comment by leledumbo** [comment]
Great, now Lazarus exits with access violation. Damn... looks like I'll need some more time.

**Comment by mdbs99** [comment]
Don't worry.
For Lazarus I use trunk version, because I never had a problem that wasn't fixed quickly.
My env is Lazarus 1.5 r47948M FPC 2.6.5 i386-win32-win32/win64
