### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by heliosroots** [mdbs99/Greyhound#34]
What is the best way to specialize Class TghSQLTable? Any suggestions?

"User := TghSQLConnector.Tables['User'] As TMyghSQLTable;"

**Comment by mdbs99** [comment]
Hi,
I didn't understand. All Tables are TghSQLTable class.
I think isn't possible to specialize these instances -- using the current design -- because:
1- The TghSQLConnector class has a private FTables: TghSQLTableList, so you can not change;
2- The TghSQLTableList class creates new tables in property Tables, that uses GetTables private method, so you can not change too;

Why you need that?

**Comment by heliosroots** [comment]
Oi, vou continuar o issue em português...

Quero criar algumas funções de importação e exportação parar JSON e etc, e preciso de "FData: TDataSet" que esta como protegido então preciso herdar/especializar, então a unica maneira q vejo e fazer um CAST... ou usar classes helper... vc tem alguma sugestão

"User := TghSQLConnector.Tables['User'] As TMyghSQLTable;"

**Comment by mdbs99** [comment]
Você não vai conseguir fazer um cast a não ser que crie as instâncias com a classe que você quer, no exemplo é a TMyghSQLTable. Mais isso não é possível (hoje, com o design atual) então talvez criar "helper class" seria um boa tentativa. No entanto não utilizo helper class, então não sei se vai ficar OK. Por favor tente e depois me diga se funcionou.

Já faz tempo que quero retornar a este projeto e subir todas as modificações do código, necessárias para fazer o que você quer e muito mais... no entanto o tempo está curto. Mas lhe digo que esse código irá sair uma hora ou outra. Se puder aguardar...

**Comment by heliosroots** [comment]
Fazer com helpers acredito q ira funcionar...  acho q  a class Tghsqltable deve ser a mais desacoplada de todas, é que mais usamos, e acho é a que mais o usuário(progamador) vai gostar de personalizar....

obrigado pelas resposta e vou ficar aguardando as suas modificações.

**Comment by mdbs99** [comment]
Na verdade as instancias de co.Tables irão ser do tipo interface e não uma classe concreta como TghSQLTable.

O suporte a JSON (XML, etc) já estava previsto desde o início, porém nunca tive demanda pra fazer um código mais apurado. Com as melhorias no design iremos ganhar esse suporte também.
